version: '3'

services:
  web:
    build: web
    restart: always
    volumes:
      - ./web:/var/app
      - ./.media/:/etc/shtolets/media
    environment:
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: 1234
      PG_HOST: db
    depends_on:
      - db

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web/static:/etc/nginx/bundle/static
      - ./.media/:/etc/nginx/bundle/media
    ports:
      - 80:80

  db:
    image: postgres
    restart: always
    volumes:
      - ./.data:/var/app/data
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      PGDATA: /var/app/data
